services:
  backend:
    container_name: maquina-giro-api
    restart: always
    build:
      context: ./api/
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
    env_file:
      - .env
    networks:
      - app-network

  frontend:
    container_name: maquina-giro-app
    restart: always
    build:
      context: ./app/
      dockerfile: Dockerfile
    ports:
      - '80:80'
    env_file:
      - .env
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge
