networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.0.0/24

services:
  backend:
    container_name: maquina-giro-api
    restart: always
    build:
      context: ./api/
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
    env_file:
      - .env
    networks:
      default:
        ipv4_address: 192.168.0.17
    depends_on:
      - node-red

  frontend:
    container_name: maquina-giro-app
    restart: always
    build:
      context: ./app/
      dockerfile: Dockerfile
    ports:
      - '80:80'
    env_file:
      - .env
    networks:
      - default
    depends_on:
      - backend

  node-red:
    container_name: maquina-giro-node-red
    restart: always
    build:
      context: ./node-red/
      dockerfile: Dockerfile
    ports:
      - '1880:1880'
    networks:
      - default
    volumes:
      - /home/conecsa/node_red_data:/data
    user: 1000:1000

  pgadmin:
    container_name: maquina-giro-pgadmin
    restart: always
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - '15432:80'
    networks:
      - default
