services:
  backend:
    container_name: maquina-giro-api
    restart: always
    build:
      context: ./api/
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
    env_file:
      - .env
    network_mode: host

  frontend:
    container_name: maquina-giro-app
    restart: always
    build:
      context: ./app/
      dockerfile: Dockerfile
    ports:
      - '80:80'
    env_file:
      - .env
    network_mode: host
    depends_on:
      - backend
